apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bookbarn.fullname" . }}-mongo
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "bookbarn.fullname" . }}-mongo
  template:
    metadata:
      labels:
        app: {{ include "bookbarn.fullname" . }}-mongo
    spec:
      containers:
        - name: mongo
          image: {{ .Values.mongo.image }}
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "bookbarn.fullname" . }}-mongo-auth
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "bookbarn.fullname" . }}-mongo-auth
                  key: MONGO_INITDB_ROOT_PASSWORD
          volumeMounts:
            - name: data
              mountPath: /data/db
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "bookbarn.fullname" . }}-mongo-pvc
