apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bookbarn.fullname" . }}-postgres
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "bookbarn.fullname" . }}-postgres
  template:
    metadata:
      labels:
        app: {{ include "bookbarn.fullname" . }}-postgres
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgres.image }}
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ include "bookbarn.fullname" . }}-catalog-db
                  key: DB_NAME
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "bookbarn.fullname" . }}-catalog-db
                  key: DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "bookbarn.fullname" . }}-catalog-db
                  key: DB_PASSWORD
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "bookbarn.fullname" . }}-pg-pvc
